name: 'debos-radxa/build'
description: 'Radxa system build framework'
inputs:
  board:
    required: true
  distro:
    required: true
  suite:
    required: false
  flavor:
    required: true
  artifacts:
    required: false
    default: 'false'
  release-id:
    required: false
  github-token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: felipehertzer/debos-radxa
    - name: Convert flavor to variant
      shell: bash
      run: |
        if [[ "${{ inputs.flavor }}" != "cli" ]] && [[ "${{ inputs.board }}" != "rockpi-s" ]]
        then
          echo "variant=xfce4" >> $GITHUB_ENV
        else
          echo "variant=server" >> $GITHUB_ENV
        fi
    - name: Build
      shell: bash
      run: |
        docker run --rm --tty --tmpfs /dev/shm:rw,nosuid,nodev,exec,size=4g --user $(id -u) --security-opt label=disable \
        --workdir $PWD --mount "type=bind,source=$PWD,destination=$PWD" --entrypoint ./scripts/build-supported-configuration.sh godebos/debos \
        -b ${{ inputs.board }} -m ${{ inputs.distro }} -v ${{ env.variant }}
    - name: Upload artifacts
      if: inputs.artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.board }}_${{ inputs.distro }}_${{ env.variant }}
        path: ./output/*.img.*
    - name: Upload
      if: inputs.release-id != '' && inputs.github-token != ''
      uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: ./output/*.img.*
    - name: Rollback release
      if: failure() && inputs.release-id != '' && inputs.github-token != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
